# Generated by Django 5.0.3 on 2024-03-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contatos", "0002_pensamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contato",
            name="cpf",
        ),
        migrations.AddField(
            model_name="contato",
            name="email_check",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contato",
            name="mensagem",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="contato",
            name="telefone_check",
            field=models.BooleanField(default=False),
        ),
    ]
