# Generated by Django 5.0.3 on 2024-03-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contatos", "0003_remove_contato_cpf_contato_email_check_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contato",
            name="data_nascimento",
            field=models.DateField(default="1900-01-01"),
        ),
    ]
