# Generated by Django 5.0.3 on 2024-04-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contatos", "0005_delete_contato"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("data_nascimento", models.DateField(default="1900-01-01")),
                ("telefone", models.CharField(max_length=11)),
                ("telefone_check", models.BooleanField(default=False)),
                ("email", models.CharField(max_length=50)),
                ("email_check", models.BooleanField(default=False)),
                ("mensagem", models.CharField(default="", max_length=300)),
            ],
        ),
    ]
